[package]
name = "edit2"
version = "0.1.0"
description = "A quick editor and viewer for text and data files"
edition = "2021"

[lib]
name = "edit2_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chardetng = "1.0.0"
encoding_rs = "0.8.42"
percent-encoding = "2.3.2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
